name: Test React App ci/cd
permissions:
  contents: write
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-action@4.1.1
        with:
          branch: 'build'
          folder: 'gt-pages'
          env:
            ACCES_TOKEN: ${{ secrets.SECRET_TOKEN }}